name: 🌐 Build Example Site
on:
  workflow_call:
    inputs:
      uploadArtifact:
        description: 'Should site artifact be uploaded'
        required: false
        default: false
        type: boolean

jobs:
  build-docs:
    name: build documentation site
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Setup Dotnet 6.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        dotnet tool restore
    - name: Build Site
      run: |
        python3 -m pip install .
        gdxml2yml godot/doc/classes godot/modules godot/platform/android/doc_classes godot/platform/ios/doc_classes godot/platform/linuxbsd/doc_classes platform/macos/doc_classes platform/web/doc_classes platform/windows/doc_classes doc/godot/api
        gdxml2xrefmap godot/doc/classes godot/modules godot/platform/android/doc_classes godot/platform/ios/doc_classes godot/platform/linuxbsd/doc_classes platform/macos/doc_classes platform/web/doc_classes platform/windows/doc_classes doc/xrefmap/godot_xrefmap.yml
        dotnet tool run docfx doc/docfx.json
    - name: Add baseUrl to xrefmap
      run: |
        sed -i '2 i baseUrl: https://gddoc2yml.nickmaltbie.com/' doc/_site/xrefmap.yml
    - name: Upload Artifact
      if: ${{ inputs.uploadArtifact }}
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: doc/_site/
        retention-days: 1

  build-example-site:
    name: build example site
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2
    steps:
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory $GITHUB_WORKSPACE
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Tools
      run: |
        export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
        dotnet tool restore
        python3 -m pip install gddoc2yml
    - name: Build Example Site
      run: |
        export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
        cd examples
        godot -v -e --path project --headless --quit-after 100
        mkdir -p project/doc/godot
        godot --path project --doctool doc/godot
        godot --path project --doctool doc/classes --gdscript-docs res://scripts
        gdxml2yml --filter project/doc/classes project/doc/classes project/doc/godot godot-docs-link/api
        dotnet tool run docfx godot-docs-link/docfx.json
    - name: Upload Artifact
      if: ${{ inputs.uploadArtifact }}
      uses: actions/upload-artifact@v4
      with:
        name: example-site
        path: examples/godot-docs-link/_site/
        retention-days: 1

  combine-artifacts:
    if: ${{ inputs.uploadArtifact }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: [build-docs, build-example-site]
    steps:
    - name: Download Docs
      uses: actions/download-artifact@v4
      with:
        name: docs
        path: _site/

    - name: Download Docs
      uses: actions/download-artifact@v4
      with:
        name: example-site
        path: _site/example

    - name: Fix permissions
      run: |
        chmod -c -R +rX "doc/_site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload Site Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: doc/_site
        name: github-pages
