name: Publish to PyPI.org

on:
  push:
    tags:
      - '*'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/gddoc2yml
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build flake8 coverage twine
        python -m pip install -r requirements.txt
    - name: Lint With Flake8
      run: |
        flake8 . --show-source
    - name: Run Tests and Coverage Report
      run: |
        coverage run -m unittest discover
        coverage report -m
    - name: Verify Build and Package
      run: |
        python -m build
        python -m twine check dist/*
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  markdown-lint:
    name: 🧹 Markdown lint
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g markdownlint-cli
      - run: markdownlint .
